---
# handlers file for systemd

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart systemd-logind
  ansible.builtin.service:
    name: systemd-logind
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  when:
    - ansible_os_family != "Suse"
